### ISSUE TITLE
Problemas na recuperação dos dados

### ISSUE THREAD

**Issue by M3nin0** [filipemeneses/fatec-posso-faltar#1]
Opa! Cara depois de atualizar o possoFaltar não consigo mais recuperar as informações do SIGA, já testei com redes diferentes, e mesmo assim ele fica travado na tela <code>Carregando tela de faltas parciais...
</code>

Você sabe o que pode ser ? Há alguma mudança que preciso fazer ?

Lembrando que tentei usando apenas as informações do exemplo.

**Comment by filipemeneses** [comment]
Talvez seja o login e senha que estão errados

**Comment by M3nin0** [comment]
Resolvido com a troca das tags =D. Valeu
